# Generated by Django 4.2.7 on 2023-12-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0003_registrhistlpu_registrpeople'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('caption', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_request_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pid', models.IntegerField()),
                ('enp', models.CharField(max_length=16)),
                ('date_attach_b', models.DateField()),
                ('date_attach_e', models.DateField(null=True)),
                ('attach_method', models.IntegerField()),
                ('area_type', models.IntegerField()),
                ('area_id', models.CharField(max_length=64, null=True)),
                ('mo_id', models.CharField(max_length=64)),
                ('mo_code', models.CharField(max_length=6)),
                ('mo_f_id', models.CharField(max_length=64, null=True)),
                ('doctor_id', models.CharField(max_length=64, null=True)),
                ('snils_doctor', models.CharField(max_length=14, null=True)),
                ('doctor_since', models.DateField(null=True)),
                ('mo_dep_id', models.CharField(max_length=64)),
                ('rs_err', models.CharField(max_length=10, null=True)),
                ('ferzl_err', models.CharField(max_length=10, null=True)),
                ('remark_err', models.CharField(max_length=500)),
                ('remark', models.CharField(max_length=500, null=True)),
                ('user', models.CharField(max_length=64)),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='attach.statusattach')),
            ],
            options={
                'indexes': [models.Index(fields=['pid', 'enp', 'mo_code', 'date_attach_b', 'date_attach_e'], name='attach_regi_pid_f27a44_idx')],
            },
        ),
    ]
